// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjbaVOsbPCYdiE6dlT87LToBZVWHXnCkU',
    appId: '1:421247859029:web:d2283ae7af800a0c77d7dc',
    messagingSenderId: '421247859029',
    projectId: 'smart-travel-assistant-001',
    authDomain: 'smart-travel-assistant-001.firebaseapp.com',
    storageBucket: 'smart-travel-assistant-001.firebasestorage.app',
    measurementId: 'G-6TY0N3XNGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMpbCGx46OVUoTYflWpSZWVA8MJLbBjM4',
    appId: '1:421247859029:android:27f364fd5d5af6f177d7dc',
    messagingSenderId: '421247859029',
    projectId: 'smart-travel-assistant-001',
    storageBucket: 'smart-travel-assistant-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxDVehq9Tz-GvH97Da1PcYG1xlth6zBmQ',
    appId: '1:421247859029:ios:a0d44c75399093fe77d7dc',
    messagingSenderId: '421247859029',
    projectId: 'smart-travel-assistant-001',
    storageBucket: 'smart-travel-assistant-001.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxDVehq9Tz-GvH97Da1PcYG1xlth6zBmQ',
    appId: '1:421247859029:ios:a0d44c75399093fe77d7dc',
    messagingSenderId: '421247859029',
    projectId: 'smart-travel-assistant-001',
    storageBucket: 'smart-travel-assistant-001.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjbaVOsbPCYdiE6dlT87LToBZVWHXnCkU',
    appId: '1:421247859029:web:de62cc40b1e666f577d7dc',
    messagingSenderId: '421247859029',
    projectId: 'smart-travel-assistant-001',
    authDomain: 'smart-travel-assistant-001.firebaseapp.com',
    storageBucket: 'smart-travel-assistant-001.firebasestorage.app',
    measurementId: 'G-XTBL7GQ8MX',
  );
}
